export { TribunalAdapter, SearchCriteria, Movement, ProtocolResponse, PetitionStatus } from './TribunalAdapter';
export { Process } from '@/types';
export { TJSCAdapter, tjscAdapter } from './TJSCAdapter';
export { TRF4Adapter, trf4Adapter } from './TRF4Adapter';
export { JFPRAdapter, jfprAdapter } from './JFPRAdapter';
export { TJPRAdapter, tjprAdapter } from './TJPRAdapter';
export { JUSTAdapter, justAdapter } from './JUSTAdapter';
export { TJMTAdapter, tjmtAdapter } from './TJMTAdapter';
export { TJROAdapter, tjroAdapter } from './TJROAdapter';
export { AdapterFactory } from './AdapterFactory';
