-- ============================================================================
-- Schema de reconstituição contábil de locação de imóveis — versão PostgreSQL
-- (Supabase), tradução de schema.sql (SQLite/sql.js).
--
-- NÃO É A FONTE DA VERDADE ENQUANTO O APP RODAR EM SQLITE. schema.sql continua
-- sendo o schema de produção; este arquivo é o alvo da migração para Postgres,
-- gerado e mantido em paralelo. Ver PLANO-POSTGRES.md para a virada.
--
-- Validado sintaticamente com `psql` (PostgreSQL 16.13) contra um cluster local
-- efêmero (createdb + este arquivo com \i) — ver seção "Verificação" no relatório
-- de entrega. Não validado contra um projeto Supabase real (extensões
-- `pgcrypto`/`pgjwt`, `auth.users` etc. — ver rls.postgres.sql).
--
-- ============================================================================
-- REGRAS DE CONVERSÃO APLICADAS (armadilhas do enunciado, uma por uma)
-- ============================================================================
--
-- 1) "INTEGER PRIMARY KEY" no SQLite é alias do rowid e autoincrementa sozinho.
--    Em Postgres isso não existe — precisa de identidade explícita. Usamos
--    `GENERATED BY DEFAULT AS IDENTITY` (padrão SQL, sucessor de SERIAL) e não
--    `GENERATED ALWAYS AS IDENTITY`: o script de carga (scripts/migrar-sqlite-
--    para-postgres.mjs) precisa inserir os ids ORIGINAIS do SQLite para
--    preservar toda referência de FK já gravada — com ALWAYS, cada INSERT
--    exigiria `OVERRIDING SYSTEM VALUE`; com BY DEFAULT, um INSERT que informa
--    o id é aceito normalmente e só quem omite a coluna recebe o próximo valor
--    da sequência. Depois da carga inicial, rode
--    `SELECT setval(pg_get_serial_sequence('<tabela>','id'), (SELECT MAX(id) FROM <tabela>))`
--    para cada tabela — sem isso, o primeiro INSERT novo colide com um id já
--    importado. O script de migração já emite esses `setval` ao final.
--
-- 2) "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP" → `timestamptz NOT NULL
--    DEFAULT now()`. Datetime "nu" (sem DEFAULT, ex: data_fechamento,
--    concluido_em) → `timestamptz` sem default. Usamos timestamptz (não
--    "timestamp without time zone"): os valores gravados por
--    `datetime('now')` no SQLite são UTC "sem fuso" — timestamptz normaliza
--    para UTC internamente e devolve já ajustado ao fuso da sessão, o que é o
--    comportamento certo para um sistema com usuários em fusos diferentes
--    (perito/advogado/contador não precisam estar no mesmo fuso do titular).
--    Se a aplicação hoje compara strings ISO literalmente (`datetime(?, '-30
--    days')` — ver item 2 do relatório), o tipo timestamptz é compatível com
--    comparação por `now() - interval`.
--
-- 3) "DATE" no SQLite é TEXT sem validação — aceita '', '31/12/2024',
--    '2024-13-40' sem reclamar. Em Postgres, `date` é um tipo real e REJEITA
--    tudo isso (confirmado empiricamente neste ambiente: `INSERT INTO d VALUES
--    ('')` e `('31/12/2024')` retornam "invalid input syntax for type date").
--    Isso é uma melhoria (passa a existir uma garantia que hoje não existe),
--    mas pode quebrar a CARGA de dado já salvo. Colunas DATE deste schema
--    populadas por texto digitado por humano (baixo risco) foram deixadas
--    `date` sem ressalva. As de risco REAL, com uma rota de entrada que já
--    tem hoje um fallback capaz de gravar string fora do formato ISO, estão
--    marcadas abaixo com "-- RISCO DATE:" e devem ser conferidas no arquivo
--    .sqlite real antes da carga (ver scripts/migrar-sqlite-para-postgres.mjs,
--    que valida e reporta cada valor de DATE que não bate com `\d{4}-\d{2}-\d{2}`
--    antes de gerar o INSERT em vez de deixar o Postgres rejeitar no meio da
--    carga). O caso concreto já identificado no código: `normalizarData()` em
--    src/domain/parsers/csv.ts faz `return bruta` (a string crua, sem
--    conversão) quando o valor não bate nem com `YYYY-MM-DD` nem com
--    `DD/MM/YYYY` — ou seja, `transacoes.data` e (por extensão)
--    `importacao_linhas.data` já podem conter data malformada vinda de CSV de
--    banco com formato atípico, hoje aceita em silêncio pelo SQLite.
--
-- 4) "REAL" para dinheiro: SQLite não tem type REAL de 4 bytes como o `real`
--    do Postgres — REAL no SQLite é sempre double de 8 bytes (mesma largura de
--    `double precision`). Ou seja, um mapeamento ingênuo REAL→real PERDERIA
--    precisão adicional (32 em vez de 64 bits) ALÉM do problema de fundo, que
--    é usar ponto flutuante binário para dinheiro: 0.1 + 0.2 não fecha exato
--    em double nem em SQLite nem em Postgres, e somas de centavos ao longo de
--    milhares de lançamentos produzem centavo fantasma que não bate no
--    balancete. RECOMENDAÇÃO (aplicada abaixo): `numeric(14,2)` para toda
--    coluna que é valor monetário em R$; `numeric(9,4)` para percentual/taxa
--    (precisa de mais casas que 2 — ex: 0.62% a.m.); `numeric(9,6)` para
--    frações/áreas. numeric é aritmética decimal exata (mesma família do
--    DECIMAL do padrão SQL) — impossível gerar centavo fantasma por
--    representação binária.
--    IMPACTO NO CÓDIGO (não corrigido aqui, só documentado): o driver `pg`
--    devolve coluna `numeric` como STRING (não `number`), justamente para não
--    reintroduzir erro de ponto flutuante ao trafegar por JS — todo código que
--    hoje faz `transacao.valor + outro.valor` ou passa o valor lido direto pra
--    conta matemática (a MAIORIA dos módulos de cálculo, ex:
--    src/domain/contabilidade, src/domain/financiamento,
--    src/domain/erp/ledger.ts) precisa parsear (`Number(x)` — reintroduzindo o
--    mesmo float — ou, melhor, uma lib decimal tipo decimal.js/big.js) antes
--    de operar, e formatar de volta como string com 2 casas ao gravar. Isso é
--    uma mudança de código real e abrangente, não cosmética — sinalizada aqui,
--    não feita (regra deste trabalho é não tocar em src/**).
--
-- 5) `CHECK (x IN (...))` — sintaxe idêntica nos dois bancos. Conferido: os
--    valores usados nos CHECK deste schema não têm acento nem aspas duplas
--    (são todos identificadores técnicos: 'apartamento', 'igpm', 'aberto' etc)
--    — nenhum precisou de escape adicional. Os poucos textos com acento do
--    schema (comentários, `descricao`) são dados de coluna livre, não valor de
--    CHECK, e nenhum problema de encoding aparece contanto que o banco
--    Postgres seja criado com `ENCODING 'UTF8'` (padrão do Supabase).
--
-- 6) `INTEGER` usado como boolean (`CHECK (x IN (0,1))`) → `boolean` nativo,
--    com `DEFAULT true/false` no lugar de `DEFAULT 1/0` e sem o CHECK (o tipo
--    já garante o domínio). Onze colunas neste schema são desse padrão — lista
--    completa nos comentários "-- era INTEGER 0/1" ao lado de cada uma.
--    IMPACTO NO CÓDIGO: `src/db/connection.ts::executar/consultar` tipam
--    parâmetros como `(string | number | null)[]` — não há `boolean` na união.
--    Todo INSERT/UPDATE que hoje manda `0`/`1` para essas 11 colunas (grep por
--    `financiado`, `uso_pessoal`, `revisado` etc — listado no item 2 do
--    relatório) precisaria mandar `true`/`false` (ou o driver `pg` aceitar
--    0/1 por coerção, o que NÃO faz para `boolean` — rejeita com erro de
--    tipo). Toda leitura que compara `row.revisado === 1` ou `=== 0` também
--    quebra, porque o valor volta como `true`/`false`, não `1`/`0`. E toda
--    consulta SQL que hoje escreve `WHERE revisado = 1` (não achei nenhuma no
--    código atual além dos módulos de teste, mas é o padrão SQLite) precisaria
--    virar `WHERE revisado` ou `WHERE revisado = true`.
--
-- 7) `UNIQUE` com NULL: TESTADO empiricamente neste ambiente (sql.js e
--    Postgres 16 reais, não de memória) — os dois bancos tratam NULL do MESMO
--    jeito por padrão: NULL nunca é igual a NULL num índice UNIQUE, então duas
--    linhas com a mesma combinação onde a coluna nullable é NULL nas duas NÃO
--    colidem, em NENHUM dos dois motores. Ou seja, ao contrário do que se
--    poderia supor, isto NÃO é uma diferença de comportamento entre SQLite e
--    Postgres — é um comportamento padrão SQL que os dois já compartilham. O
--    caso concreto do enunciado, `lotes_importacao UNIQUE
--    (arquivo_hash_sha256, conta_id)` com `conta_id` anulável, já tem esse
--    "furo" HOJE, em SQLite: reimportar o mesmo arquivo sem conta associada
--    (conta_id NULL) cria um segundo lote em vez de reabrir o existente — o
--    comentário original da tabela ("Reimportar o mesmo arquivo... reabre o
--    lote existente") só é verdade quando conta_id está preenchido. A migração
--    para Postgres NÃO piora nem resolve isso sozinha. O que a migração TORNA
--    POSSÍVEL, e que o SQLite não tem: `UNIQUE ... NULLS NOT DISTINCT`
--    (Postgres 15+), que trataria dois NULLs como iguais e fecharia o furo.
--    Deixamos comentado ao lado da constraint, como decisão explícita de
--    produto (mudaria comportamento observável — dois lotes sem conta viram
--    um só — o que pode ser desejado ou não).
--
-- ============================================================================
-- Achados ADICIONAIS de conversão (fora da lista do enunciado, encontrados na
-- leitura linha a linha):
--
-- a) Identificador `balancete_OK` (ledger_encerramentos) tem letra maiúscula.
--    Sem aspas, Postgres FOLDA todo identificador não citado para minúsculo:
--    a coluna nasce `balancete_ok`. `src/domain/fechamento/periodos.ts` lê
--    `encerramento?.balancete_OK` (case exato) — contra Postgres isso viria
--    `undefined` porque a linha devolvida pelo driver tem a chave
--    `balancete_ok`. Renomeada para `balancete_ok` (minúsculo) aqui, já que é
--    o nome real que o Postgres usaria de qualquer forma — CORRIGIR
--    src/domain/fechamento/periodos.ts (linhas 51 e 67) e o teste
--    periodos.test.ts:106 é trabalho de código, fora do escopo deste pacote,
--    mas está sinalizado no relatório e em PLANO-POSTGRES.md.
--
-- b) `imovel_gestao_ledger_integration.ts:746` faz `date(datetime('now'))` —
--    hoje um truque de cast duplo do SQLite; em Postgres a forma direta é
--    `CURRENT_DATE` ou `now()::date`. Sinalizado no item 2 do relatório.
--
-- ============================================================================

-- ---------------------------------------------------------------------------
-- CONTAS BANCÁRIAS E PATRIMÔNIO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS contas_bancarias (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banco           text NOT NULL,
    agencia         text,
    numero          text NOT NULL,
    titular         text NOT NULL,
    tipo            text NOT NULL CHECK (tipo IN ('corrente', 'poupanca', 'investimento')),
    ativa_desde     date,
    observacoes     text,
    -- Ver nota 7 acima: agencia é anulável e UNIQUE trata NULL como distinto
    -- em ambos os bancos — comportamento preservado, não é regressão.
    UNIQUE (banco, agencia, numero)
);

CREATE TABLE IF NOT EXISTS imoveis (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apelido         text NOT NULL,
    tipo            text NOT NULL CHECK (tipo IN ('apartamento', 'kitnet', 'sala_comercial', 'vaga_garagem', 'outro')),
    cidade          text,
    endereco        text,
    fracao_ideal    numeric(9,6) CHECK (fracao_ideal IS NULL OR fracao_ideal > 0), -- era REAL; fração 0-1, precisa de casas decimais finas
    area_m2         numeric(10,2),                                                -- era REAL
    financiado      boolean NOT NULL DEFAULT false,                                -- era INTEGER 0/1
    uso_pessoal     boolean NOT NULL DEFAULT false,                                -- era INTEGER 0/1

    matricula               text,
    matricula_mae           text,
    valor_aquisicao         numeric(14,2),           -- era REAL (dinheiro)
    valor_venal_atual       numeric(14,2),           -- era REAL (dinheiro)
    data_avaliacao_venal    date,
    regime_patrimonial      text NOT NULL DEFAULT 'proprio' CHECK (regime_patrimonial IN ('proprio', 'gestao_terceiros')),
    proprietario_nome       text,
    co_titular_nome         text
);

CREATE TABLE IF NOT EXISTS imovel_inventario_bens (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id           integer NOT NULL REFERENCES imoveis(id),
    descricao           text NOT NULL,
    valor_reposicao     numeric(14,2),           -- era REAL (dinheiro)
    data_vistoria       date
);

CREATE TABLE IF NOT EXISTS financiamentos (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    instituicao     text NOT NULL,
    sistema         text NOT NULL CHECK (sistema IN ('SAC', 'PRICE', 'OUTRO')),
    valor_contratado numeric(14,2) NOT NULL,             -- era REAL (dinheiro)
    taxa_juros_mensal numeric(9,4) NOT NULL DEFAULT 0.8,  -- era REAL (percentual a.m.)
    data_contrato   date NOT NULL,
    parcelas_total  integer NOT NULL,

    saldo_devedor_manual        numeric(14,2),   -- era REAL (dinheiro)
    parcela_mensal_manual       numeric(14,2),   -- era REAL (dinheiro)
    data_referencia_saldo_manual date,

    observacoes     text
);

CREATE TABLE IF NOT EXISTS dividas_consumo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                    text NOT NULL CHECK (tipo IN ('consignado', 'emprestimo_pessoal', 'cartao_parcelado', 'outro')),
    instituicao             text NOT NULL,
    valor_contratado        numeric(14,2),          -- era REAL (dinheiro)
    saldo_devedor_atual     numeric(14,2) NOT NULL, -- era REAL (dinheiro)
    parcela_mensal          numeric(14,2) NOT NULL, -- era REAL (dinheiro)
    data_referencia_saldo   date NOT NULL,
    observacoes             text
);

CREATE TABLE IF NOT EXISTS obras (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    descricao       text NOT NULL,
    data_inicio     date,
    data_fim        date,
    natureza        text NOT NULL CHECK (natureza IN ('capex', 'manutencao')),
    valor_total     numeric(14,2)   -- era REAL (dinheiro)
);

CREATE TABLE IF NOT EXISTS prestadores (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            text NOT NULL,
    cpf_cnpj        text,
    servico         text NOT NULL
);

-- ---------------------------------------------------------------------------
-- CONTRATOS DE LOCAÇÃO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS contratos_locacao (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    locatario       text NOT NULL,
    tipo            text NOT NULL CHECK (tipo IN ('residencial_fixo', 'airbnb_temporada')),
    valor_referencia numeric(14,2) NOT NULL,     -- era REAL (dinheiro)
    dia_vencimento  integer,
    -- RISCO DATE: data_inicio/data_fim vêm de formulário de cadastro (input
    -- type=date do navegador, formato ISO garantido pelo próprio input) — risco
    -- baixo, mas confira no .sqlite real antes da carga (ver item 3 acima).
    data_inicio     date NOT NULL,
    data_fim        date,
    indice_reajuste text CHECK (indice_reajuste IN ('igpm', 'ipca', 'nenhum')) DEFAULT 'igpm',

    percentual_aluguel_efetivo numeric(9,4) NOT NULL DEFAULT 100 CHECK (percentual_aluguel_efetivo BETWEEN 0 AND 100), -- era REAL

    multa_percentual numeric(9,4) NOT NULL DEFAULT 2.0,             -- era REAL
    multa_ate_dias integer NOT NULL DEFAULT 5,
    multa_percentual_substitutiva numeric(9,4) NOT NULL DEFAULT 10.0, -- era REAL
    juros_mensal_percentual numeric(9,4) NOT NULL DEFAULT 1.0,      -- era REAL
    indice_correcao_mora text CHECK (indice_correcao_mora IN ('igpm', 'ipca', 'nenhum')) DEFAULT 'ipca',
    honorarios_percentual numeric(9,4) NOT NULL DEFAULT 0,          -- era REAL
    dias_gatilho_judicial integer NOT NULL DEFAULT 9999,

    percentual_reajuste_primeira_renovacao numeric(9,4),            -- era REAL
    duracao_minima_meses integer NOT NULL DEFAULT 12,

    multa_rescisoria_teto_meses numeric(9,4) NOT NULL DEFAULT 3,    -- era REAL

    observacoes     text
);

CREATE TABLE IF NOT EXISTS contrato_reajustes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id         integer NOT NULL REFERENCES contratos_locacao(id),
    data_vigencia       date NOT NULL,
    valor_anterior      numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    valor_novo          numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    percentual_aplicado numeric(9,4) NOT NULL,    -- era REAL
    criterio            text NOT NULL CHECK (criterio IN ('fixo', 'igpm', 'ipca')),
    eh_reajuste_anual   boolean NOT NULL DEFAULT true,  -- era INTEGER 0/1
    observacoes         text
);

CREATE TABLE IF NOT EXISTS contrato_locatarios (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id     integer NOT NULL REFERENCES contratos_locacao(id),
    nome            text NOT NULL,
    cpf             text,
    papel           text NOT NULL CHECK (papel IN ('locatario', 'responsavel_solidario')),
    telefone        text,
    email           text
);

CREATE TABLE IF NOT EXISTS caucoes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id         integer NOT NULL REFERENCES contratos_locacao(id),
    valor_inicial       numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    data_deposito       date NOT NULL,
    indice_correcao     text NOT NULL CHECK (indice_correcao IN ('poupanca', 'igpm', 'ipca', 'nenhum')),
    data_devolucao      date,
    valor_devolvido     numeric(14,2),           -- era REAL (dinheiro)
    deducoes_descricao  text,
    deducoes_valor      numeric(14,2) DEFAULT 0, -- era REAL (dinheiro)
    observacoes         text
);

CREATE TABLE IF NOT EXISTS contrato_custeio_rubricas (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id     integer NOT NULL REFERENCES contratos_locacao(id),
    referencia      text,
    descricao       text NOT NULL,
    percentual      numeric(9,4),   -- era REAL
    valor_base      numeric(14,2)   -- era REAL (dinheiro)
);

CREATE TABLE IF NOT EXISTS contrato_franquia_hidrica (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id             integer NOT NULL REFERENCES contratos_locacao(id),
    ocupacao_pessoas        integer NOT NULL,
    franquia_total_m3       numeric(10,3),   -- era REAL
    custo_estimado_reais    numeric(14,2)    -- era REAL (dinheiro)
);

CREATE TABLE IF NOT EXISTS indices_economicos (
    indice          text NOT NULL CHECK (indice IN ('poupanca', 'igpm', 'ipca')),
    -- RISCO DATE: mes_referencia é digitado como "primeiro dia do mês" —
    -- confira que todo valor gravado é um dia 01 válido (ex: 2023-01-01), sem
    -- variação de formato, antes da carga.
    mes_referencia  date NOT NULL,
    taxa_mensal     numeric(9,4) NOT NULL,   -- era REAL (percentual do mês)
    PRIMARY KEY (indice, mes_referencia)
);

CREATE TABLE IF NOT EXISTS declaracoes_fiscais (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano_calendario                  integer NOT NULL,
    tipo                            text NOT NULL CHECK (tipo IN ('dirpf_anual', 'carne_leao_mensal')),
    mes_referencia                  date,
    rendimento_tributavel_declarado numeric(14,2) NOT NULL, -- era REAL (dinheiro)
    imposto_pago                    numeric(14,2),          -- era REAL (dinheiro)
    fonte_documento                 text,
    observacoes                     text
);

-- ---------------------------------------------------------------------------
-- PLANO DE CONTAS DO APP E TRANSAÇÕES
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS plano_de_contas (
    codigo          text PRIMARY KEY,
    descricao       text NOT NULL,
    grupo           text NOT NULL CHECK (grupo IN ('receita', 'despesa', 'pessoal', 'transferencia')),
    natureza        text NOT NULL CHECK (natureza IN ('debito', 'credito'))
);

CREATE TABLE IF NOT EXISTS transacoes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id            integer NOT NULL REFERENCES contas_bancarias(id),
    -- RISCO DATE — o mais alto do schema: normalizarData() em
    -- src/domain/parsers/csv.ts devolve a string CRUA quando ela não bate com
    -- YYYY-MM-DD nem DD/MM/YYYY (comentário 3 no topo do arquivo). Um .sqlite
    -- real pode já ter linha com `data` fora do formato ISO vinda de um CSV de
    -- banco com layout de data atípico. scripts/migrar-sqlite-para-postgres.mjs
    -- varre e reporta cada valor de `data`/`data_documento` que não bate com
    -- `\d{4}-\d{2}-\d{2}` ANTES de gerar o INSERT.
    data                date NOT NULL,
    data_competencia    date,                     -- opcional; mês do fato gerador (ver schema.sql)
    valor               numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    descricao_original  text NOT NULL,
    fitid               text,
    documento_fonte      text,
    plano_conta_codigo  text REFERENCES plano_de_contas(codigo),
    imovel_id           integer REFERENCES imoveis(id),
    contrato_id         integer REFERENCES contratos_locacao(id),
    prestador_id        integer REFERENCES prestadores(id),
    categorizado_por    text CHECK (categorizado_por IN ('regra', 'ia', 'manual')),
    revisado            boolean NOT NULL DEFAULT false,  -- era INTEGER 0/1
    UNIQUE (conta_id, fitid)
);

CREATE TABLE IF NOT EXISTS rateios (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transacao_id    integer NOT NULL REFERENCES transacoes(id),
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    criterio        text NOT NULL,
    percentual      numeric(9,6) NOT NULL CHECK (percentual > 0 AND percentual <= 1), -- era REAL (fração 0-1)
    valor_rateado   numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    base_incompleta boolean NOT NULL DEFAULT false   -- era INTEGER 0/1
);

CREATE TABLE IF NOT EXISTS regras_categorizacao (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    padrao              text NOT NULL,
    plano_conta_codigo  text NOT NULL REFERENCES plano_de_contas(codigo),
    imovel_id           integer REFERENCES imoveis(id),
    criado_em           date NOT NULL
);

CREATE TABLE IF NOT EXISTS documentos (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                        text NOT NULL CHECK (tipo IN ('contrato', 'recibo', 'fatura', 'nota_fiscal', 'pedido_comercial', 'boleto', 'outro')),
    arquivo_nome                text NOT NULL,
    valor                       numeric(14,2),   -- era REAL (dinheiro)
    -- RISCO DATE: data_documento é extraído por regex/OCR de texto livre de
    -- PDF (ver comentário original da tabela) — risco de formato inválido é
    -- real e maior que o de transacoes.data. Confira antes da carga.
    data_documento              date,
    cnpj_cpf_contraparte        text,
    nome_contraparte            text,
    descricao_produto_servico   text,
    plano_conta_codigo          text REFERENCES plano_de_contas(codigo),
    texto_extraido              text,
    criado_em                   date NOT NULL,
    observacoes                 text
);

CREATE TABLE IF NOT EXISTS documento_imoveis (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id    integer NOT NULL REFERENCES documentos(id),
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    percentual      numeric(6,3) NOT NULL DEFAULT 100 CHECK (percentual > 0 AND percentual <= 100) -- era REAL (0-100, não 0-1)
);

CREATE TABLE IF NOT EXISTS documento_transacoes (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id    integer NOT NULL REFERENCES documentos(id),
    transacao_id    integer NOT NULL REFERENCES transacoes(id),
    score           numeric(6,4) NOT NULL,   -- era REAL (confiança do casamento automático)
    status          text NOT NULL CHECK (status IN ('sugerido', 'confirmado', 'rejeitado')) DEFAULT 'sugerido',
    UNIQUE (documento_id, transacao_id)
);

CREATE TABLE IF NOT EXISTS regras_categorizacao_documentos (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_cpf            text NOT NULL UNIQUE,
    tipo                text NOT NULL CHECK (tipo IN ('contrato', 'recibo', 'fatura', 'nota_fiscal', 'pedido_comercial', 'boleto', 'outro')),
    nome_contraparte    text,
    plano_conta_codigo  text REFERENCES plano_de_contas(codigo),
    imovel_id           integer REFERENCES imoveis(id),
    criado_em           date NOT NULL,
    atualizado_em       date NOT NULL
);

CREATE TABLE IF NOT EXISTS documentos_gerados (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            text NOT NULL CHECK (tipo IN ('laudo_pericial', 'rad')),
    nome_arquivo    text NOT NULL,
    data_emissao    date NOT NULL,
    gerado_em       timestamptz NOT NULL,   -- era TEXT (timestamp ISO 8601 completo) — vira timestamptz de verdade
    hash_sha256     text NOT NULL,
    tamanho_bytes   integer NOT NULL,
    contrato_id     integer REFERENCES contratos_locacao(id),
    imovel_id       integer REFERENCES imoveis(id)
);

-- log_alteracoes: dados_anteriores/dados_novos guardam snapshot JSON como TEXT
-- no SQLite. Mantido `text` aqui (não convertido para `jsonb`) de propósito:
-- é uma trilha de auditoria imutável, e o valor precisa continuar sendo
-- byte-a-byte o que foi gravado no momento do fato — reformatar para jsonb
-- reordenaria/normalizaria chaves e mudaria a representação textual, o que é
-- inaceitável numa trilha que pode ser usada como prova. Se quiser consultar
-- por dentro do JSON, crie uma VIEW com `dados_novos::jsonb` em cima, sem
-- alterar a coluna de armazenamento.
CREATE TABLE IF NOT EXISTS log_alteracoes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela              text NOT NULL,
    registro_id         integer NOT NULL,
    operacao            text NOT NULL CHECK (operacao IN ('criacao', 'edicao', 'exclusao')),
    quando              timestamptz NOT NULL,   -- era TEXT (timestamp ISO 8601 completo)
    resumo              text NOT NULL,
    dados_anteriores    text,
    dados_novos         text
);

CREATE INDEX IF NOT EXISTS idx_documentos_gerados_tipo ON documentos_gerados(tipo);
CREATE INDEX IF NOT EXISTS idx_log_alteracoes_tabela_registro ON log_alteracoes(tabela, registro_id);

CREATE INDEX IF NOT EXISTS idx_transacoes_data ON transacoes(data);
CREATE INDEX IF NOT EXISTS idx_transacoes_imovel ON transacoes(imovel_id);
CREATE INDEX IF NOT EXISTS idx_transacoes_contrato ON transacoes(contrato_id);
CREATE INDEX IF NOT EXISTS idx_caucoes_contrato ON caucoes(contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_locatarios_contrato ON contrato_locatarios(contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_reajustes_contrato ON contrato_reajustes(contrato_id);
CREATE INDEX IF NOT EXISTS idx_documentos_data ON documentos(data_documento);
CREATE INDEX IF NOT EXISTS idx_documento_imoveis_documento ON documento_imoveis(documento_id);
CREATE INDEX IF NOT EXISTS idx_documento_transacoes_documento ON documento_transacoes(documento_id);
CREATE INDEX IF NOT EXISTS idx_documento_transacoes_transacao ON documento_transacoes(transacao_id);

-- ---------------------------------------------------------------------------
-- VISTORIAS
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vistorias (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id       integer NOT NULL REFERENCES imoveis(id),
    contrato_id     integer REFERENCES contratos_locacao(id),
    data_agendada   timestamptz,
    data_realizada  timestamptz,
    responsavel     text,
    status          text NOT NULL CHECK (status IN ('agendada', 'em_progresso', 'concluida', 'aprovada')) DEFAULT 'agendada',
    observacoes     text,
    valor_estimado  numeric(14,2),   -- era REAL (dinheiro)
    criado_em       timestamptz NOT NULL DEFAULT now(),
    atualizado_em   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vistoria_item (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id     integer NOT NULL REFERENCES vistorias(id),
    tipo            text NOT NULL CHECK (tipo IN ('dano', 'necessidade_reparo', 'achado_positivo')),
    descricao       text NOT NULL,
    severidade      text CHECK (severidade IN ('baixa', 'media', 'alta')),
    valor_estimado  numeric(14,2),   -- era REAL (dinheiro)
    criado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vistoria_anexo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id     integer NOT NULL REFERENCES vistorias(id),
    tipo            text CHECK (tipo IN ('foto', 'documento', 'laudo')),
    url_storage     text,
    mime_type       text,
    tamanho_bytes   integer,
    criado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vistoria_log (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id     integer NOT NULL REFERENCES vistorias(id),
    acao            text NOT NULL CHECK (acao IN ('agendada', 'inspecao_iniciada', 'concluida', 'aprovada', 'rejeitada')),
    usuario_id      integer,
    motivo          text,
    criado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vistorias_imovel ON vistorias(imovel_id);
CREATE INDEX IF NOT EXISTS idx_vistorias_contrato ON vistorias(contrato_id);
CREATE INDEX IF NOT EXISTS idx_vistorias_status ON vistorias(status);
CREATE INDEX IF NOT EXISTS idx_vistoria_item_vistoria ON vistoria_item(vistoria_id);
CREATE INDEX IF NOT EXISTS idx_vistoria_anexo_vistoria ON vistoria_anexo(vistoria_id);
CREATE INDEX IF NOT EXISTS idx_vistoria_log_vistoria ON vistoria_log(vistoria_id);

-- ---------------------------------------------------------------------------
-- ERP: LEDGER CONTÁBIL INTEGRADO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS entidades_legais (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            text NOT NULL CHECK (tipo IN ('pessoa_fisica', 'pessoa_juridica')),
    cpf_cnpj        text NOT NULL UNIQUE,
    nome            text NOT NULL,
    endereco        text,
    regime_tributario text CHECK (regime_tributario IN ('simples_nacional', 'presumido', 'lucro_real')),
    criado_em       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS periodos_contabeis (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_id     integer NOT NULL REFERENCES entidades_legais(id),
    ano             integer NOT NULL,
    mes             integer NOT NULL CHECK (mes BETWEEN 1 AND 12),
    status          text NOT NULL CHECK (status IN ('aberto', 'fechado')) DEFAULT 'aberto',
    saldo_anterior_caixa numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    data_abertura   timestamptz NOT NULL DEFAULT now(),
    data_fechamento timestamptz,
    encerrado_por   integer,
    motivo_encerramento text,
    UNIQUE (entidade_id, ano, mes)
);

CREATE TABLE IF NOT EXISTS centros_custo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_id     integer NOT NULL REFERENCES entidades_legais(id),
    codigo          text NOT NULL,
    descricao       text NOT NULL,
    tipo            text NOT NULL CHECK (tipo IN ('imavel', 'administrativo', 'operacional')),
    ativo           boolean NOT NULL DEFAULT true,   -- era INTEGER 0/1
    UNIQUE (entidade_id, codigo)
);

CREATE TABLE IF NOT EXISTS contas_plano_contas (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_id     integer NOT NULL REFERENCES entidades_legais(id),
    codigo          text NOT NULL,
    descricao       text NOT NULL,
    grupo           text NOT NULL CHECK (grupo IN ('ativo', 'passivo', 'patrimonio_liquido', 'receita', 'despesa', 'resultado')),
    natureza        text NOT NULL CHECK (natureza IN ('debito', 'credito')),
    analisavel      boolean NOT NULL DEFAULT true,   -- era INTEGER 0/1
    ativo           boolean NOT NULL DEFAULT true,   -- era INTEGER 0/1
    UNIQUE (entidade_id, codigo)
);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_id         integer NOT NULL REFERENCES entidades_legais(id),
    periodo_id          integer NOT NULL REFERENCES periodos_contabeis(id),
    centro_custo_id     integer REFERENCES centros_custo(id),
    conta_id            integer NOT NULL REFERENCES contas_plano_contas(id),

    data_lancamento     date NOT NULL,

    valor_debito        numeric(14,2) CHECK (valor_debito IS NULL OR valor_debito > 0),   -- era REAL (dinheiro)
    valor_credito       numeric(14,2) CHECK (valor_credito IS NULL OR valor_credito > 0), -- era REAL (dinheiro)

    descricao           text NOT NULL,

    origem_modulo       text NOT NULL CHECK (origem_modulo IN (
        'transacoes', 'contratos', 'patrimonio', 'caucao', 'financiamento',
        'rateio', 'rateios', 'vistorias', 'advocacia', 'contas-pessoais',
        'imovel-gestao', 'apontamento-prestador', 'pagamentos-integracao',
        'skillos', 'manual'
    )),
    origem_id           integer NOT NULL,
    referencia_documento text NOT NULL,

    criado_em           timestamptz NOT NULL DEFAULT now(),
    criado_por          integer,

    auditada            boolean NOT NULL DEFAULT false,   -- era INTEGER 0/1
    auditado_em         timestamptz,
    auditado_por        integer,

    -- Auto-referência (estorno). O script de carga precisa inserir todos os
    -- lançamentos primeiro com estornado_por_id NULL e só então rodar um
    -- UPDATE para preencher os estornos — ou usar `SET CONSTRAINTS ...
    -- DEFERRED` numa única transação, já que a FK abaixo aponta para a
    -- própria tabela e a linha referenciada pode ter sido inserida depois.
    estornado_por_id    integer REFERENCES ledger_entries(id) DEFERRABLE INITIALLY DEFERRED,
    motivo_estorno      text,

    -- Vínculo inverso do estorno: se esta linha é a reversão, qual lançamento ela reverte.
    -- É o que distingue, no INSERT, reversão deliberada de reimportação duplicada — ver o
    -- índice parcial idx_ledger_origem_unica abaixo.
    estorno_de_id       integer REFERENCES ledger_entries(id) DEFERRABLE INITIALLY DEFERRED,

    -- A unicidade da origem é o índice parcial idx_ledger_origem_unica, não uma constraint
    -- de tabela: unicidade condicional só existe em CREATE UNIQUE INDEX.
    CHECK (
        (valor_debito IS NOT NULL AND valor_credito IS NULL) OR
        (valor_debito IS NULL AND valor_credito IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS ledger_saldos_periodo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id      integer NOT NULL REFERENCES periodos_contabeis(id),
    conta_id        integer NOT NULL REFERENCES contas_plano_contas(id),
    saldo_anterior  numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    total_debito    numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    total_credito   numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    saldo_final     numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    atualizado_em   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (periodo_id, conta_id)
);

-- Nome de coluna normalizado para minúsculo (era `balancete_OK` no SQLite —
-- ver "Achados adicionais" no topo do arquivo). Ajustar
-- src/domain/fechamento/periodos.ts (linhas 51 e 67) e
-- src/domain/fechamento/periodos.test.ts:106 é trabalho de código, fora do
-- escopo deste pacote, mas obrigatório antes da virada (ver PLANO-POSTGRES.md).
CREATE TABLE IF NOT EXISTS ledger_encerramentos (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id      integer NOT NULL REFERENCES periodos_contabeis(id),
    data_encerramento timestamptz NOT NULL DEFAULT now(),
    encerrado_por   integer,
    total_debito    numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    total_credito   numeric(14,2) DEFAULT 0,   -- era REAL (dinheiro)
    balancete_ok    boolean NOT NULL DEFAULT false,   -- era INTEGER 0/1, coluna `balancete_OK`
    hash_snapshot   text,
    observacoes     text
);

CREATE TABLE IF NOT EXISTS regras_contabilizacao (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_id     integer NOT NULL REFERENCES entidades_legais(id),
    origem_modulo   text NOT NULL,
    tipo_operacao   text NOT NULL,
    conta_debito_id integer REFERENCES contas_plano_contas(id),
    conta_credito_id integer REFERENCES contas_plano_contas(id),
    descricao       text,
    UNIQUE (entidade_id, origem_modulo, tipo_operacao)
);

CREATE INDEX IF NOT EXISTS idx_ledger_periodo ON ledger_entries(periodo_id);
CREATE INDEX IF NOT EXISTS idx_ledger_conta ON ledger_entries(conta_id);
CREATE INDEX IF NOT EXISTS idx_ledger_data ON ledger_entries(data_lancamento);
CREATE INDEX IF NOT EXISTS idx_ledger_origem ON ledger_entries(origem_modulo, origem_id);

-- No máximo UMA perna VIVA por (documento de origem, conta) — ver o comentário longo em
-- schema.sql. A constraint de tabela anterior, UNIQUE (origem_modulo, origem_id, conta_id),
-- quebrava todo estorno: a reversão copia a tripla inteira do original. O índice indexa a
-- mesma tripla, mas exclui a reversão e o original já revertido.
-- 'manual' fica FORA deste índice — ver comentário equivalente em schema.sql.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ledger_origem_unica
    ON ledger_entries(origem_modulo, origem_id, conta_id)
    WHERE estorno_de_id IS NULL AND estornado_por_id IS NULL AND origem_modulo != 'manual';
CREATE INDEX IF NOT EXISTS idx_ledger_auditada ON ledger_entries(auditada);

CREATE INDEX IF NOT EXISTS idx_saldos_periodo ON ledger_saldos_periodo(periodo_id);
CREATE INDEX IF NOT EXISTS idx_encerramentos_periodo ON ledger_encerramentos(periodo_id);

-- ---------------------------------------------------------------------------
-- PORTAL PRESTADOR: APONTAMENTOS E REMUNERAÇÃO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS apontamentos_diarios (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id        integer NOT NULL REFERENCES prestadores(id),
    data                date NOT NULL,
    entrada             text NOT NULL,
    saida_intervalo     text,
    retorno_intervalo   text,
    saida_final         text NOT NULL,
    status              text NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'enviado', 'aprovado', 'retificado')),
    observacoes         text,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (prestador_id, data)
);

CREATE TABLE IF NOT EXISTS historico_horarios (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apontamento_id      integer NOT NULL REFERENCES apontamentos_diarios(id) ON DELETE CASCADE,
    tipo_evento         text NOT NULL CHECK (tipo_evento IN ('chegada', 'saida_intervalo', 'retorno', 'saida')),
    horario             text NOT NULL,
    horario_original    text,
    justificativa_retificacao text,
    criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS itens_remuneraveis (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apontamento_id      integer NOT NULL REFERENCES apontamentos_diarios(id) ON DELETE CASCADE,
    tipo                text NOT NULL CHECK (tipo IN ('diaria', 'airbnb', 'urgencia', 'deslocamento', 'materiais', 'extra')),
    rubrica             text NOT NULL,
    valor_base          numeric(14,2) NOT NULL,          -- era REAL (dinheiro)
    adicional_percentual numeric(9,4) DEFAULT 0,          -- era REAL
    valor_final         numeric(14,2) NOT NULL,          -- era REAL (dinheiro)
    observacao          text,
    criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS movimentacoes_financeiras (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apontamento_id      integer NOT NULL REFERENCES apontamentos_diarios(id) ON DELETE CASCADE,
    tipo                text NOT NULL CHECK (tipo IN ('vale', 'emprestimo', 'adiantamento')),
    valor               numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    data_solicitacao    date NOT NULL,
    data_aprovacao      date,
    data_desconto       date,
    motivo              text,
    status              text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'descontado', 'rejeitado')),
    criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fechamentos_semanais (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id        integer NOT NULL REFERENCES prestadores(id),
    data_inicio         date NOT NULL,
    data_fim            date NOT NULL,
    valor_bruto         numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    descontos_total     numeric(14,2) DEFAULT 0,  -- era REAL (dinheiro)
    valor_liquido       numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    status              text NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto', 'fechado', 'aprovado', 'pago')),
    aprovado_em         timestamptz,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (prestador_id, data_inicio, data_fim)
);

CREATE TABLE IF NOT EXISTS emprestimos (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id        integer NOT NULL REFERENCES prestadores(id),
    valor_original      numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    taxa_juros          numeric(9,4) NOT NULL,    -- era REAL (percentual mensal)
    parcelas_total      integer NOT NULL,
    parcelas_pagas      integer DEFAULT 0,
    valor_total_com_juros numeric(14,2) NOT NULL, -- era REAL (dinheiro)
    data_contratacao    date NOT NULL,
    data_vencimento     date NOT NULL,
    status              text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'pago', 'cancelado')),
    observacao          text,
    criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS retificacoes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apontamento_id      integer NOT NULL REFERENCES apontamentos_diarios(id) ON DELETE CASCADE,
    campo_alterado      text NOT NULL,
    valor_anterior      text,
    valor_novo          text,
    motivo              text,
    data_retificacao    date NOT NULL,
    aprovada_em         timestamptz,
    observacao          text,
    criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parametros_operacionais (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametro           text NOT NULL,
    valor               numeric(14,4),   -- era REAL — parâmetro genérico (ex: preço do litro), não necessariamente R$ com 2 casas; mantido com mais casas por segurança
    valor_descricao     text,
    vigencia_inicio     date NOT NULL,
    vigencia_fim        date,
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (parametro, vigencia_inicio)
);

CREATE INDEX IF NOT EXISTS idx_apontamentos_prestador_data ON apontamentos_diarios(prestador_id, data);
CREATE INDEX IF NOT EXISTS idx_apontamentos_status ON apontamentos_diarios(status);
CREATE INDEX IF NOT EXISTS idx_historico_horarios_apontamento ON historico_horarios(apontamento_id);
CREATE INDEX IF NOT EXISTS idx_itens_remuneraveis_apontamento ON itens_remuneraveis(apontamento_id);
CREATE INDEX IF NOT EXISTS idx_itens_remuneraveis_tipo ON itens_remuneraveis(tipo);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_apontamento ON movimentacoes_financeiras(apontamento_id);
CREATE INDEX IF NOT EXISTS idx_fechamentos_prestador_data ON fechamentos_semanais(prestador_id, data_inicio);
CREATE INDEX IF NOT EXISTS idx_fechamentos_status ON fechamentos_semanais(status);
CREATE INDEX IF NOT EXISTS idx_emprestimos_prestador ON emprestimos(prestador_id);
CREATE INDEX IF NOT EXISTS idx_emprestimos_status ON emprestimos(status);
CREATE INDEX IF NOT EXISTS idx_retificacoes_apontamento ON retificacoes(apontamento_id);
CREATE INDEX IF NOT EXISTS idx_parametros_operacionais_parametro ON parametros_operacionais(parametro, vigencia_inicio);

-- ---------------------------------------------------------------------------
-- COFRE DE EVIDÊNCIAS E TRIAGEM DE IMPORTAÇÃO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lotes_importacao (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo_nome        text NOT NULL,
    arquivo_hash_sha256 text NOT NULL,
    arquivo_bytes       integer NOT NULL,
    tipo_detectado      text NOT NULL,
    conta_id            integer REFERENCES contas_bancarias(id),
    status              text NOT NULL CHECK (status IN ('em_triagem', 'concluido', 'descartado')) DEFAULT 'em_triagem',
    importado_em        timestamptz NOT NULL DEFAULT now(),
    concluido_em        timestamptz,
    total_linhas        integer NOT NULL DEFAULT 0,
    observacoes         text,
    -- Ver nota 7 no topo do arquivo: conta_id é anulável. Em SQLite E em
    -- Postgres (por padrão), duas linhas com o mesmo hash e conta_id = NULL
    -- NÃO colidem — o "reabre o lote existente" do comentário original só
    -- funciona quando conta_id está preenchido; isso é comportamento herdado,
    -- não uma regressão da migração. Descomente a linha abaixo (Postgres
    -- 15+) SOMENTE se for uma decisão deliberada de fechar esse furo — ela
    -- muda comportamento observável (reimportar o mesmo arquivo sem conta
    -- passaria a reabrir um único lote em vez de criar outro):
    --   ALTER TABLE lotes_importacao DROP CONSTRAINT lotes_importacao_arquivo_hash_sha256_conta_id_key;
    --   ALTER TABLE lotes_importacao ADD CONSTRAINT lotes_importacao_arquivo_hash_sha256_conta_id_key
    --     UNIQUE NULLS NOT DISTINCT (arquivo_hash_sha256, conta_id);
    UNIQUE (arquivo_hash_sha256, conta_id)
);

CREATE TABLE IF NOT EXISTS importacao_linhas (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id             integer NOT NULL REFERENCES lotes_importacao(id),
    linha_numero        integer NOT NULL,
    -- RISCO DATE: mesma origem de risco de transacoes.data (é a mesma pipeline
    -- de parsing, antes da aprovação em linha de transacoes) — ver nota 3 no
    -- topo do arquivo.
    data                date,
    valor               numeric(14,2),   -- era REAL (dinheiro)
    descricao_original  text NOT NULL,
    fitid               text,
    plano_conta_codigo  text REFERENCES plano_de_contas(codigo),
    status              text NOT NULL CHECK (status IN (
        'pendente', 'aprovada', 'rejeitada', 'duplicata_provavel', 'malformada'
    )) DEFAULT 'pendente',
    motivo              text,
    transacao_id        integer REFERENCES transacoes(id),
    duplicata_de_id     integer REFERENCES transacoes(id),
    decidido_em         timestamptz,
    decidido_por        text,
    UNIQUE (lote_id, linha_numero)
);

CREATE INDEX IF NOT EXISTS idx_importacao_linhas_lote ON importacao_linhas(lote_id, status);
CREATE INDEX IF NOT EXISTS idx_importacao_linhas_transacao ON importacao_linhas(transacao_id);
CREATE INDEX IF NOT EXISTS idx_lotes_importacao_hash ON lotes_importacao(arquivo_hash_sha256);

-- auditoria_log: todas as colunas de "timestamp"/data aqui eram TEXT solto no
-- SQLite (sem NOT NULL, sem formato garantido — compliance-audit-log.ts grava
-- o que a aplicação formatar). Mantidas como `text` propositalmente: são uma
-- trilha encadeada por hash (hash_sha256/hash_anterior) — assim como
-- log_alteracoes, o valor gravado precisa continuar sendo exatamente o que
-- entrou no hash da cadeia; converter para timestamptz mudaria a
-- representação e quebraria qualquer verificação de hash já calculada sobre
-- o texto antigo. Se for reescrito do zero para Postgres (sem migrar dado
-- histórico), aí sim vale `timestamptz` — decisão de produto, não técnica.
CREATE TABLE IF NOT EXISTS auditoria_log (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp"             text,
    usuario_id              integer,
    usuario_nome            text,
    ip_origem               text,
    modulo_chamador         text,
    tipo_operacao           text,
    entidade_afetada        text,
    id_entidade             integer,
    descricao_alteracao     text,
    valor_anterior          text,
    valor_novo              text,
    hash_sha256             text,
    hash_anterior           text,
    status                  text,
    mensagem_erro           text,
    tempo_processamento_ms  integer,
    retencao_ate            text,
    assinado                boolean DEFAULT false,   -- era INTEGER 0/1 (DEFAULT 0, sem NOT NULL — preservado)
    assinatura_digital      text,
    criado_em               text
);

CREATE INDEX IF NOT EXISTS idx_auditoria_log_entidade ON auditoria_log(entidade_afetada, id_entidade);
CREATE INDEX IF NOT EXISTS idx_auditoria_log_timestamp ON auditoria_log("timestamp");

-- ---------------------------------------------------------------------------
-- CONCILIAÇÃO BANCÁRIA
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS extrato_saldos_informados (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id        integer NOT NULL REFERENCES contas_bancarias(id),
    data            date NOT NULL,
    saldo           numeric(14,2) NOT NULL,   -- era REAL (dinheiro)
    informado_em    timestamptz NOT NULL DEFAULT now(),
    informado_por   text,
    observacoes     text,
    UNIQUE (conta_id, data)
);

CREATE TABLE IF NOT EXISTS conciliacoes_bancarias (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id                        integer NOT NULL REFERENCES contas_bancarias(id),
    data_corte                      date NOT NULL,
    saldo_extrato                   numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    saldo_transacoes                numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    saldo_razao                     numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    diferenca_extrato_transacoes    numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    diferenca_transacoes_razao      numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    diferenca_extrato_razao         numeric(14,2) NOT NULL,  -- era REAL (dinheiro)
    fechada_sem_diferenca           boolean NOT NULL DEFAULT false,  -- era INTEGER 0/1
    realizada_em                    timestamptz NOT NULL DEFAULT now(),
    realizada_por                   text,
    observacoes                     text
);

CREATE INDEX IF NOT EXISTS idx_conciliacoes_bancarias_conta ON conciliacoes_bancarias(conta_id, data_corte);

CREATE TABLE IF NOT EXISTS conciliacoes_itens (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conciliacao_id      integer NOT NULL REFERENCES conciliacoes_bancarias(id),
    tipo                text NOT NULL CHECK (tipo IN (
        'nao_lancada_no_razao', 'triagem_pendente', 'classificacao_pendente',
        'lancamento_orfao_no_razao', 'residual_nao_identificado'
    )),
    descricao           text NOT NULL,
    quantidade          integer NOT NULL DEFAULT 0,
    valor               numeric(14,2) NOT NULL DEFAULT 0,   -- era REAL (dinheiro)
    afeta_diferenca     boolean NOT NULL DEFAULT true,      -- era INTEGER 0/1
    referencias_json     jsonb NOT NULL DEFAULT '[]'::jsonb  -- era TEXT NOT NULL DEFAULT '[]'; aqui pode virar jsonb de verdade (não é trilha de auditoria por hash, é lista de ids para a UI reconsultar)
);

CREATE INDEX IF NOT EXISTS idx_conciliacoes_itens_conciliacao ON conciliacoes_itens(conciliacao_id);

-- ============================================================================
-- Fim. 51 tabelas (mesma contagem de schema.sql). Índices e PRIMARY/FOREIGN
-- KEY mantidos 1:1. `PRAGMA foreign_keys = ON` do topo do schema.sql não tem
-- equivalente aqui porque não precisa: FKs são sempre aplicadas em Postgres,
-- não são uma opção de sessão.
-- ============================================================================
