{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucide-crmt.secretName" . }}
  namespace: {{ include "lucide-crmt.namespace" . }}
  labels:
    {{- include "lucide-crmt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.API_KEY }}
  API_KEY: {{ .Values.secrets.API_KEY | b64enc | quote }}
  {{- else }}
  API_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.SESSION_SECRET }}
  SESSION_SECRET: {{ .Values.secrets.SESSION_SECRET | b64enc | quote }}
  {{- else }}
  SESSION_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ENCRYPTION_MASTER_SECRET }}
  ENCRYPTION_MASTER_SECRET: {{ .Values.secrets.ENCRYPTION_MASTER_SECRET | b64enc | quote }}
  {{- end }}
{{- end }}
